# Updated 24-02-2019
# Path = /config/packages/nas.yaml

# V0.86.0 Breaking & Lovelace changes 24-01-2019
# Changed over to Lovelace 26-01-2019
# Changed unit_of_measurement: "ºC" -> unit_of_measurement: "°C" 24-02-2019

homeassistant:

  customize:
    sensor.nas_1_uptime:
       icon: mdi:nas 
    sensor.disk_1_state:
       icon: mdi:harddisk
    sensor.disk_1_temperature:
       icon: mdi:thermometer 
    sensor.disk_1_status_state:
       icon: mdi:harddisk
    sensor.disk_2_state:
       icon: mdi:harddisk
    sensor.disk_2_temperature:
       icon: mdi:thermometer 
    sensor.disk_2_status_state:
       icon: mdi:harddisk
    sensor.raid_status_state:
       icon: mdi:harddisk
    sensor.fan_status_state:
       icon: mdi:fan
 
#group:
#  NAS 1 Status: 
#    control: hidden
#    entities:
#      - sensor.nas_1_uptime
#      - sensor.disk_1_state 
#      - sensor.disk_1_temperature
#      - sensor.disk_1_status_state
#      - sensor.disk_2_state
#      - sensor.disk_2_temperature
#      - sensor.disk_2_status_state
#      - sensor.fan_status_state
#      - sensor.raid_status_state
    
sensor:

#-----------------------------------------------------------------------------#
# Synology NAS 1 Uptime
# Converts 100's of a second (TimeTick) to Days, Hours & Minutes 
  - platform: snmp
    version: 2c
    scan_interval: 60
    accept_errors: true
    name: "NAS 1 Uptime"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read 
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >-
        {% set timetick = value | int %}
        {% set minutes = ((timetick % 360000) / 6000) | int%}
        {% set hours = ((timetick % 8640000) / 360000) | int %}
        {% set days = (timetick / 8640000) | int %}
        {%- if timetick < 6000 -%}
          Less than a minute
        {%- else -%}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hr
            {%- else -%}
              {{ hours }} hrs
            {%- endif -%}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if days > 0 or hours > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if minutes == 1 -%}
              1 min
            {%- else -%}
              {{ minutes }} min
            {%- endif -%}
          {%- endif -%}
        {%- endif -%}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 120
    accept_errors: true
    name: "Disk 1 Temperature"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.2.1.1.6.0
    unit_of_measurement: "°C"
#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 60
    accept_errors: true
    name: "Disk 1 Status"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.2.1.1.5.0
#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 120
    accept_errors: true
    name: "Disk 2 Temperature"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.2.1.1.6.1
    unit_of_measurement: "°C"
#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 60
    accept_errors: true
    name: "Disk 2 Status"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.2.1.1.5.1
#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 120
    accept_errors: true
    name: "Raid Status"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.3.1.1.3.0
#-----------------------------------------------------------------------------#
  - platform: snmp
    scan_interval: 120
    accept_errors: true
    name: "Fan Status"
    host: 192.168.0.12
    port: 161
    community: !secret snmp_read  
    baseoid: 1.3.6.1.4.1.6574.1.4.1.0
#-----------------------------------------------------------------------------#

    
  - platform: template
    sensors:
#-----------------------------------------------------------------------------#
     raid_status_state:
       value_template: '{% if is_state("sensor.raid_status", "1") %}Normal{% else %}Degraded{% endif %}'
       friendly_name: 'Raid Status'        
#-----------------------------------------------------------------------------#
     disk_1_status_state:
       value_template: '{% if is_state("sensor.disk_1_status", "1") %}Good{% else %}Failed{% endif %}'
       friendly_name: 'Disk 1 Status'        
#-----------------------------------------------------------------------------#
     disk_2_status_state:
       value_template: '{% if is_state("sensor.disk_2_status", "1") %}Good{% else %}Failed{% endif %}'
       friendly_name: 'Disk 2 Status'        
#-----------------------------------------------------------------------------#
     disk_1_state:
       value_template: '{% if is_state("sensor.disk_1_temperature", "0") %}Sleeping{% else %}Online{% endif %}'
       friendly_name: 'Disk 1'        
#-----------------------------------------------------------------------------#
     disk_2_state:
       value_template: '{% if is_state("sensor.disk_1_temperature", "0") %}Sleeping{% else %}Online{% endif %}'
       friendly_name: 'Disk 2'        
#-----------------------------------------------------------------------------#
     fan_status_state:
       value_template: '{% if is_state("sensor.fan_status", "1") %}OK{% else %}Failed{% endif %}'
       friendly_name: 'Fan Status'        
#-----------------------------------------------------------------------------#
