# Updated 11-05-2018

###############################################################################
# This script is called from "automation.alarm_live_frontdoor"
###############################################################################
front_door_alarm:
    alias: 'Front Door Alarm'
    sequence:
      - delay:
          # supports seconds, milliseconds, minutes, hours
          seconds: 60
      - service: switch.turn_on
        data:
          entity_id: 
            #- switch.test_led_2 #Pretend Siren
            - switch.alarm_siren
      - service: notify.alarm
        data_template:
          title: "Alarm"
          message: "Sorry to disturb you Sir, but the Front Door sensor has been activated it seems we have an intruder"                 
      - delay:
          # supports seconds, milliseconds, minutes, hours
          seconds: 30
###############################################################################





          
          