# Updated 10-02-2018
# Working now I didn't understand how service & scripts worked :-)
# Updated to reflect switch chamges in V0.61.1
# Removed Apple TV Media Player & added Apple TV to Broadlink

###############################################################################
# Control The Lounge Media devices via a Broadlink RM2 #
###############################################################################
tv:
    alias: TV
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgBgAAABJpEUERQRExEUERQRExEUNRQRFDUUNhM2FDUUNRQ2ExEUNhMRFDYTERQRFDUUERQRExEUNRQRFDUUNhMRFDUUNhQ1FAAFFAABJkgUAAw8AAEmSBQADDwAASZIFAANBQAAAAAAAAAA'
#-----------------------------------------------------------------------------#

sky:
    alias: Sky
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgAwAFgdDhANEA4eDR4dDw4PDg8OEA4PHB4dDw4PDh4ODw4PDg8OEA4PHBANHg4PDgANBQAAAAAAAAAA'
#-----------------------------------------------------------------------------#

dvd:
    alias: DVD
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet:
            - 'JgCEAyoRFhEqERYSFhEWESoRKhEqAAGYUREqERYRKhEWEikSFhEWERYSKRIWESoRKhEWESoRFhIWERYRKhEqESoAAZhRESoRFhEqERYSKRIWERYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWESoRFhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIqERYRKhEWESoSFRIWERYRKhEWEikSKRIWESoRFhIWERYRKhEqESoAAZdREikSFhEqERYRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ETKBIWESoRFhEqERcRFhEWESoRFxEpEikSFRIqERYSFhEWESoRKhEqAAGXURIpEhYRKhEWESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEqERYRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWESoRFhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIpEhYRKhEWESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEqERYRKhEWEhYRFhEqERYSKRIpEhYRKhIVERYSFhEqESoRKgABl1ESKRIWESoRFhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIpEhYRKhEWESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEqEhURKhEWEhYRFhEqERYSKRIpEhYRKhEWERcSFREqESoRKgABl1ESKhEWESoRFhEqEhYRFhEWESoRFxEpEikSFhEqERYSFhEWESoRKhEqAAGYUREqERYRKhEWEikSFhIVERYSKRIWESoRKhEWESoRFhIWERYRKhEqESoAAZdREikSFhEqERYRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWESoRFhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIpEhYRKhEWESoRFhIWERYRKhEWEikSKRIWESkSFhEWEhYRKRIpEikAAZhRESoRFhIpEhYRKhEWERYSFhEqERYRKhEqEhUSKRIWERYRFhIpEikSKQANBQAAAAA='            
#-----------------------------------------------------------------------------#
            
amplifier:
    alias: Amplifier
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet:
            - 'JgBoAAABJZMSExE4ERMSNxI4ETgROBETEjcSExE4ERQRExITERMSNxI3EjcSNxI4ETgRExITERMSExETEhMRExITETgROBI3EgAFIAABJUoSAAxDAAElShIADEQAASRLEQAMRAABJUoSAA0F'            
#-----------------------------------------------------------------------------#

pause_sky:
    alias: Pause Sky
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgAuAFgdDg8OEA4dDh4dDw4PDg8OEA4PHB4dDw4PDh4ODw4PDg8dHg4PHB4ODw4ADQUAAAAAAAAAAAAA'
#-----------------------------------------------------------------------------#

pause_dvd:
    alias: Pause DVD
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgCEAykSFhEqERYRFhIWESoRKhEqAAGXURIpEhYRFhEqESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWERYRKhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURMoEhYRFhEqESoSFhEWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWERYRKhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIpEhYRFhEqESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREikSFhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKQABmFERKhEWEhYRKhEqERYRFhIWESoRFhEqESoRFhIpEhYRFhEWEikSKRIpAAGYUREqERYSFhEqESoRFhEWEhYRKhEWESoRKhEWEikSFhEWERYSKRIpEikAAZhRESoRFhIWESoRKhEWERYSFhEqERYRKhEqERYSKRIWERYRFhIpEikSKQABmFERKhEWEhYRKRIpEhYRFhEWEikSFhEqESoRFhEqERYSFhEWESoRKhEqAAGYUREqERYRFhIpEikSFhEWERYSKRIWESoRKhEWESoRFhIWERYRKhEqESoAAZhRESoRFhEWEikSKRIWERYRFhIpEhYRKRIpEhYRKhEWERYSFhEqESoRKgABl1ESKRIWERYRKhEqERYSFhEWESoRFhIpEikSFhEpEhYRFhIWESoRKRIpAAGYURIpEhYRFhEqESoRFhEWEhYRKhEWESoRKhEWEikSFhEWERYSKRIpEikAAZhRESoRFhIWESoRKhEWERYSFhEqERYRKhEqERYRKhEWEhYRFhEqESoRKgABmFERKhEWERYSKRIpEhYRFhEWEikSFhEqESkSFhEqERYSFhEWESoRKhEqAAGXURIpEhYRFhEqESoRFhIWERYRKhEWEikSKRIWESkSFhEWEhUSKRIpEikAAZhRESoRFhIWESoRKhEWERYSFhEqERYRKhEqERYSKRIWERYRFhIpEikSKQANBQAAAAA='
#-----------------------------------------------------------------------------#

play_dvd:
    alias: Play DVD
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgCEAykSFhEqERYRFhIWESoRKhEqAAGXURIWESoRFhEqESoRFhIWERYRKhIVEikSKRIWESoRFhEWEhYRKhEqESoAAZdREhYRKhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESFhEqERYRKhEqERYSFhEWESoRFhIpESoSFhEqERYRFhIWESoRKhEqAAGXURIWESoRFhEqESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREhYRKhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESFhEqERYRKhEqERYSFhEWESoRFhIpEikSFhEqERYRFhIWESoRKhEqAAGXURIWESoRFhEqESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREhYRKhIVESoSKRIWERYRFhEqEhYRKRIpEhYRKhEWEhYRFhEqESoRKgABl1IRFhEqERYSKRIpEhYRFhEWESoSFhEqESoRFhEqERYSFhEWESoRKhEqAAGYUREWESoRFhIpEikSFhEWERYSKRIWESoRKhEWESoRFhIWERYRKhEqESoAAZhRERYRKhEWEikSKRIWERYRFhIpEhYRKhEqERYRKhEWEhYRFhEqESoRKgABl1IRFhEqERYSKRIpEhYRFhEWESoRFhIpEikSFhEqERYRFxEWESoRKhEqAAGXURIWESoRFhEqESoRFhIWERYRKhEWEikSKRIWESoRFhEWEhYRKhEqESoAAZdREhYRKhEWESoRKhEWEhYRFhEqERYSKRIpEhYRKhEWERYSFhEqESoRKgABl1ESFhEqERYRKhEqERYSFhEWESoRFhEqESoRFxEpEhYRFhEXESkSKRIpAAGYUREWEikSFhEqESoRFhEWEhYRKhEWESoRKhEWEikSFhEWERYSKRIpEikAAZhRERYSKRIWESoRKhEWERYSFhEqERYRKhEqERYSKRIWERYRFhIpEikSKQABmFESFhEpEhYRKhEqERYRFxEWESoRFhEqESoRFhIpEhYRFhEXESkSKRIpAAGYUREXESkSFhEqESoRFhEXERYRKhEWESoRKhEWEikSFhEWERcRKRIpEikAAZhREhYRKhEWESoRKhEWEhYRFhEqERYSKREqERYSKRIWERYSFhEpEikSKQANBQAAAAA='
#-----------------------------------------------------------------------------#

pause_apple_tv:
    alias: Pause Apple TV
    sequence:
      - service: switch.broadlink_send_packet_192_168_0_150
        data:
          packet: 
            - 'JgBIAAABK5AVEBQ1FDQVNBUQFDUUNRQ0FTQVNBU0FBEUERQQFRAUNRQRFDQVNBU0FTQVEBQ1FBAVNBU0FTQUERQRFBAVEBQ1FQANBQ'
###############################################################################

