# Updated 30-04-2017
# Path = /config/switches/broadlink_ir.yaml

# Doing all the TV and Media via scripts now

###############################################################################
# Broadlink IR / RF Blaster #
###############################################################################
 - platform: broadlink
   host: !secret broadlink_lounge
   mac: '34:EA:34:F4:35:4C'
   timeout: 15
#   switches:
###############################################################################

###############################################################################
# Door Bell RF Code #
###############################################################################
#    door_bell:
#      friendly_name: "Door Bell"
#      command_on: 'sgUsABkbGRoaGhozGZgaZhl+GpgamBqXGWUaZRllGn8afhl/GpgafhlmGn4ZAAKnAAAAAAAAAAAAAAAA'
#      command_off: ''
###############################################################################
    

