# Updated 09-08-2018
# Changed to Back Porch Laser 31-03-2018
# Combined all the TP-Link power points into one file 27-05-2018
# Added TP 7

###############################################################################
# The are all the TP-Link Power Points                                        #
###############################################################################

###############################################################################
# Installed in Mum's Loft for the Laser Display in The Back Porch #
###############################################################################
 - platform: tplink
   host: !secret tp_1
   name: "Back Porch Laser"
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in the Lounge For Christmas Lights #
###############################################################################
 - platform: tplink
   host: !secret tp_2
   name: "Christmas Lounge Window"   
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in the Lounge For the Christmas Tree Lights #
###############################################################################
 - platform: tplink
   host: !secret tp_3
   name: "Christmas Tree"   
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in a Kitchen Cupboard for Christmas Lights in the back Porch #
###############################################################################
 - platform: tplink
   host: !secret tp_4
   name: "Christmas Back Porch" 
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in The Bat Cave for Christmas Lights in the Hallway & Bat Cave #
###############################################################################
 - platform: tplink
   host: !secret tp_5
   name: "Christmas The Bat Cave" 
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in The Bat Cave controls my Fan  #
###############################################################################
 - platform: tplink
   host: !secret tp_6
   name: "Bat Cave Fan" 
#-----------------------------------------------------------------------------# 

###############################################################################
# Installed in The Hallway Front Garden Christmas Lights / Garage  #
###############################################################################
 - platform: tplink
   host: !secret tp_7
   name: "Christmas Front Garden" 
#-----------------------------------------------------------------------------# 

###############################################################################
  