# Updated 28-10-2017
# Path = /config/lights/front_porch_light.yaml

###############################################################################
# Front Porch Light #
###############################################################################
 - platform: mqtt
   name: "Front Porch Light"
   state_topic: "stat/Front-Porch/POWER"
   command_topic: "cmnd/Front-Porch/POWER"
   availability_topic: "tele/Front-Porch/LWT"
   qos: 0
   payload_on: "ON"
   payload_off: "OFF"
   payload_available: "Online"
   payload_not_available: "Offline"  
   optimistic: false
   retain: true
###############################################################################

