# Modified 07-05-2018

###############################################################################
# Customize Automations #
############################################################################### 
group.all_automations:
  friendly_name: 'All Automations'
  icon: mdi:home-automation
  hidden: false
############################################################################### 
  
  