# Updated 10-01-2019
# Path = /config/customize/computers.yaml

# Breaking down customize into separate parts 19-04-2018
# Removed some PC's 10-05-2018
# Removed ' from binary Sensor names V0.85.0 Change 10-01-2019

###############################################################################
# Customize Computers #
############################################################################### 
binary_sensor.big_mac:
  icon: mdi:desktop-mac
binary_sensor.amys_pc:
  friendly_name: "Amy's PC"
  icon: mdi:desktop-tower       
binary_sensor.sonic_music_player:
  icon: mdi:itunes      
binary_sensor.bens_xbox:
  friendly_name: "Ben's X Box"
  icon: mdi:xbox       
binary_sensor.bens_pc:
  friendly_name: "Ben's PC"
  icon: mdi:desktop-tower       
###############################################################################
