# Updated 10-05-2018
# Breaking down customize into separate parts 19-04-2018
# Removed some PC's 10-05-2018

###############################################################################
# Customize Computers #
############################################################################### 
binary_sensor.big_mac:
  icon: mdi:desktop-mac
binary_sensor.amys_pc:
  icon: mdi:desktop-tower       
binary_sensor.sonic_music_player:
  icon: mdi:itunes      
binary_sensor.bens_xbox:
  icon: mdi:xbox       
binary_sensor.bens_pc:
  icon: mdi:desktop-tower       
###############################################################################
