# Updated 31-01-2019
# Path = /config/customize/dht_sensors.yaml

# Breaking down customize into separate parts 19-04-2018
# Added Bedroom DHT 28-04-2018
# Removed Custom Names 31-01-2019

###############################################################################
# Customize DHT Sensors #
############################################################################### 
sensor.comms_temperature:
  icon: mdi:thermometer
sensor.comms_humidity:
  icon: mdi:water-percent
sensor.bedroom_temperature:
  icon: mdi:thermometer
sensor.bedroom_humidity:
  icon: mdi:water-percent
sensor.greenhouse_temperature:
  icon: mdi:thermometer
sensor.greenhouse_humidity:
  icon: mdi:water-percent  
sensor.garden_temperature:
  icon: mdi:thermometer
sensor.garden_humidity:
  icon: mdi:water-percent  
###############################################################################

###############################################################################
# Customize Lounge BroadLink RM Pro DHT Sensor #
############################################################################### 
sensor.lounge_temperature:
  friendly_name: "Lounge Temperature Raw"
  icon: mdi:thermometer        

# Lounge Temp via Broadlink RM Pro Adjusted via Template  
sensor.lounge_temperature_adjusted:
  icon: mdi:thermometer        
###############################################################################
