# Updated 19-04-2018
# Breaking down customize into separate parts 19-04-2018

###############################################################################
# Customize Door Bell Press Button #
############################################################################### 
switch.door_bell:
  friendly_name: 'Door Bell'
  icon: mdi:bell-ring
###############################################################################
