# Updated 17-05-2018
# Breaking down customize into separate parts 19-04-2018
# Added Uptime & Version Sensor 17-05-2018

###############################################################################
# Customize Jarvis Sensors #
############################################################################### 
# Jarvis CPU Temp #
sensor.cpu_temp:
  friendly_name: 'CPU Temperature'
  icon: mdi:thermometer
#-----------------------------------------------------------------------------#
# HA (Jarvis) Uptime Sensor #
sensor.jarvis_uptime:
  #friendly_name: 'Jarvis Uptime'
  icon: mdi:clock
#-----------------------------------------------------------------------------#
# Last Reboot Sensor #
sensor.since_last_boot_adjusted:
  friendly_name: 'Last Reboot'
  icon: mdi:clock
#-----------------------------------------------------------------------------#
# HA Version Sensor #
sensor.ha_installed_version:
  friendly_name: 'HA Version'
  icon: mdi:home-assistant
###############################################################################

