# Updated 19-05-2018
# Breaking down customize into separate parts 19-04-2018
# Added Lounge Reading Light 23-04-2018
# Added Front Garage Lights 19-05-2018

###############################################################################
# Customize Lights #
############################################################################### 
switch.butterfly:
  friendly_name: 'Butterfly Lights'
  icon: mdi:lightbulb
switch.hallway_night_light:
  icon: mdi:lightbulb
switch.front_porch_light:
  friendly_name: 'Front Porch Light'
  icon: mdi:lightbulb
switch.soffit_lights:
  friendly_name: 'Soffit Lights'
  icon: mdi:lightbulb
switch.fireplace_red:
  friendly_name: 'Fireplace Red'
  icon: mdi:lightbulb
switch.fireplace_white:
  friendly_name: 'Fireplace White'
  icon: mdi:lightbulb 
switch.lounge_reading_light:
  icon: mdi:lightbulb     
switch.front_garage_lights:
  icon: mdi:lightbulb     
###############################################################################
