# Updated 21-04-2018

###############################################################################
# Customize Minecraft Server #
############################################################################### 
sensor.knob_wiilys_server:
  friendly_name: 'Minecraft Server'
  #icon: mdi:minecraft
###############################################################################
