# Updated 22-04-2018
# Path = /config/customize/power_switches.yaml

# Breaking down customize into separate parts 19-04-2018
# Added Comms Cupboard Fan 22-04-2018

###############################################################################
# Customize Power Switches #
############################################################################### 
switch.photo_frame:
  friendly_name: "Lounge Photo Frame"
  assumed_state: false
  icon: mdi:image-album
switch.comms_fan:
  icon: mdi:fan  
###############################################################################
