# Updated 19-04-2018
# Path = /config/customize/speed_test.yaml

# Breaking down customize into separate parts 19-04-2018

###############################################################################
# Customize Speed Test #
############################################################################### 
sensor.speedtest_ping:
  friendly_name: "Speedtest Ping"
  icon: mdi:clock-fast
###############################################################################

