# Updated 27-05-2018

###############################################################################
# My Test Group
############################################################################### 
switch.test_led:
  friendly_name: 'Test LED'
  icon: mdi:power-socket-uk
switch.test_led_2:
  friendly_name: 'Test LED 2'
  icon: mdi:lightbulb
#switch.door_bell:     
#  friendly_name: 'Door Bell'
#  icon: mdi:doorbell-video
binary_sensor.test_switch:
  friendly_name: 'Test Binary Sensor Switch'
  icon: mdi:toggle-switch
############################################################################### 
