# Pinched from https://github.com/ntalekt/homeassistant
# Last Modified 03-05-2018

###############################################################################
# Countdown for Birthdays & Christmas Nor sure what I will use it for yet
###############################################################################
- platform: command_line
  name: Christmas
  unit_of_measurement: days
  scan_interval: 3600
  command: "XMAS=`date -d 'Dec 25' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($XMAS - $TODAY)); echo $DAYS"    
#-----------------------------------------------------------------------------#
- platform: command_line
  name: Birthday Ralph
  unit_of_measurement: days
  scan_interval: 3600
  command: "BDAY=`date -d 'Oct 9' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"  
#-----------------------------------------------------------------------------#
- platform: command_line
  name: Birthday Ben
  unit_of_measurement: days
  scan_interval: 3600
  command: "BDAY=`date -d 'Oct 11' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"  
#-----------------------------------------------------------------------------#
- platform: command_line
  name: Birthday Amy
  unit_of_measurement: days
  scan_interval: 3600
  command: "BDAY=`date -d 'Jan 16' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"  
#-----------------------------------------------------------------------------#
- platform: command_line
  name: Birthday Tracy
  unit_of_measurement: days
  scan_interval: 3600
  command: "BDAY=`date -d 'Jan 25' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"  
#-----------------------------------------------------------------------------#
- platform: command_line
  name: Birthday Mum
  unit_of_measurement: days
  scan_interval: 3600
  command: "BDAY=`date -d 'Nov 26' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; DAYS=$(($BDAY - $TODAY)); echo $DAYS"  
###############################################################################
   
    




    