# Updated 21-04-2018
# Path = /config/sensors/dark_sky.yaml

###############################################################################
# Dark Sky
###############################################################################
- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
   - summary
   #- daily_summary
   - precip_intensity
   - precip_type
   - precip_probability
   - temperature
   - humidity
   - wind_speed
   - cloud_cover
###############################################################################
