#modified 20-04-2018

###############################################################################
# Ben's Minecraft Server Sensor #
###############################################################################
- platform: minecraft
  name: Knob Wiily's Server
  server: 192.168.0.83
###############################################################################


