#modified 19-04-2018

###############################################################################
# Season Sensor not sure what I am going to use it for yet
###############################################################################
- platform: season
  type: astronomical
###############################################################################
