# Updated 19-04-2018
# Path = /config/sensors/season.yaml

###############################################################################
# Season Sensor not sure what I am going to use it for yet
###############################################################################
- platform: season
  type: astronomical
###############################################################################
