# Updated 08-09-2018
# Trying to extend scan_interval: 30
# Added Wireless Access Points 12-02-2018
# Added DNS Server 20-03-2018
# Added 2nd DNS Server 25-03-2018
# Moved DNS 2 onto Switch 2 22-04-2018
# New Router still trying to work out how to monitor ADSL State so disabled 27-05-2018
# Network Changes 02-06-2018
# Added router Uptime and WAN Traffic Stats 08-09-2018

###############################################################################
# SNMP Monitoring
###############################################################################
# Printer Page Count
- platform: snmp
  scan_interval: 30
  accept_errors: true
  name: "Printer Page Count"
  host: 192.168.0.55
  port: 161
  community: !secret snmp_read2  
  baseoid: 1.3.6.1.2.1.43.10.2.1.4.1.1
#-----------------------------------------------------------------------------#
# Router WAN 1 Bytes In
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router WAN 1 RX"
  host: 192.168.0.1
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.5
  accept_errors: true
  unit_of_measurement: 'GB'
  #value_template: '{{((value | int) / 1000000000) | int}}'
  value_template: '{{((value | int) / 1000000000) | round(2)}}'
#-----------------------------------------------------------------------------#
# Router WAN 1 Bytes Out 
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router WAN 1 TX"
  host: 192.168.0.1
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.5
  accept_errors: true
  unit_of_measurement: 'GB'
  #value_template: '{{((value | int) / 1000000000) | int}}'
  value_template: '{{((value | int) / 1000000000) | round(2)}}'
#-----------------------------------------------------------------------------#
# Router WAN 2 Bytes In
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router WAN 2 RX"
  host: 192.168.0.1
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.6
  accept_errors: true
  unit_of_measurement: 'GB'
  #value_template: '{{((value | int) / 1000000000) | int}}'
  value_template: '{{((value | int) / 1000000000) | round(2)}}'
#-----------------------------------------------------------------------------#
# Router WAN 2 Bytes Out 
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router WAN 2 TX"
  host: 192.168.0.1
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.6
  accept_errors: true
  unit_of_measurement: 'GB'
  #value_template: '{{((value | int) / 1000000000) | int}}'
  value_template: '{{((value | int) / 1000000000) | round(2)}}'
#-----------------------------------------------------------------------------#
###############################################################################
# Router Template to add Both WAN TX & Both WAN RX Sensors together 
###############################################################################
- platform: template
  sensors:
   router_wan_rx:
     friendly_name: 'WAN In'
     unit_of_measurement: 'GB'
     value_template: >-
          {{ ( (states('sensor.router_wan_1_rx')|float) + (states('sensor.router_wan_2_rx')|float) )|round(2) }}
#-----------------------------------------------------------------------------#
- platform: template
  sensors:
   router_wan_tx:
     friendly_name: 'WAN Out'
     unit_of_measurement: 'GB'
     value_template: >-
          {{ ( (states('sensor.router_wan_1_tx')|float) + (states('sensor.router_wan_2_tx')|float) )|round(2) }}
#-----------------------------------------------------------------------------#
# Router Uptime 
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router Uptime"
  host: 192.168.0.1
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.1.3.0
  accept_errors: true
  value_template: >-
      {% set time = value | int %}
      {% set minutes = ((time % 360000) / 6000) | int%}
      {% set hours = ((time % 8640000) / 360000) | int %}
      {% set days = (time / 8640000) | int %}
      {%- if time < 6000 -%}
        Less than a minute
      {%- else -%}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if days > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if days > 0 or hours > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes == 1 -%}
            1 minute
          {%- else -%}
            {{ minutes }} minutes
          {%- endif -%}
        {%- endif -%}
      {%- endif -%}
#-----------------------------------------------------------------------------#
# Router Status Checking Switch Port 24 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Router"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.24  
#-----------------------------------------------------------------------------#
# Lounge Switch Checking Switch Port 7 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Lounge Switch"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.7
#-----------------------------------------------------------------------------#
# Bat Cave Switch Checking Switch Port 5 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Bat Cave Switch"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.5
#-----------------------------------------------------------------------------#
# POE Switch Checking Switch Port 6 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "POE Switch"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.6
#-----------------------------------------------------------------------------#
# VPN Server Checking Switch Port 21 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "VPN Server"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.21
#-----------------------------------------------------------------------------#
# Dining Room Wireless Access Point Checking Switch Port 20 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Dining Room WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.20
#-----------------------------------------------------------------------------#
# Kitchen Wireless Access Point Checking Switch Port 3 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Kitchen WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.3
#-----------------------------------------------------------------------------#
# Lounge Wireless Access Point Checking Switch Port 13 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Lounge WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.13
#-----------------------------------------------------------------------------#
# Hallway Wireless Access Point Checking Switch Port 22 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Hallway WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.22
#-----------------------------------------------------------------------------#
# Bedroom Wireless Access Point Checking Switch Port 8 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "Bedroom WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.8
#-----------------------------------------------------------------------------#
# The Burrow Wireless Access Point Checking Switch Port 16 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "The Burrow WAP"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.16
#-----------------------------------------------------------------------------#
# DNS 1 Server Checking Switch Port 19 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "DNS 1"
  host: 192.168.0.20
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.19
#-----------------------------------------------------------------------------#
# DNS 2 Server Checking Switch Port 18 is Up  
- platform: snmp
  version: 2c
  scan_interval: 30
  name: "DNS 2"
  host: 192.168.0.21
  port: 161
  community: !secret snmp_read 
  baseoid: 1.3.6.1.2.1.2.2.1.8.13
#-----------------------------------------------------------------------------#
# IP camera Server Checking Switch Port 21 is Up  
#- platform: snmp
#  version: 2c
#  scan_interval: 30
#  name: "IP Camera Server"
#  host: 192.168.0.21
#  port: 161
#  community: !secret snmp_read 
#  baseoid: 1.3.6.1.2.1.2.2.1.8.21
###############################################################################
  
###############################################################################    
# Switch Template  Switch Port Sensors 
###############################################################################
- platform: template
  sensors:
#   adsl_line_1_state:
#     value_template: '{% if is_state("sensor.adsl_line_1", "1") %}Up{% else %}Down{% endif %}'
#     friendly_name: 'ADSL Line 1'
#-----------------------------------------------------------------------------#
#   adsl_line_2_state:
#     value_template: '{% if is_state("sensor.adsl_line_2", "1") %}Up{% else %}Down{% endif %}'
#     friendly_name: 'ADSL Line 2'
#-----------------------------------------------------------------------------#
   router_state:
     value_template: '{% if is_state("sensor.router", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Router'
#-----------------------------------------------------------------------------#
   vpn_server_state:
     value_template: '{% if is_state("sensor.vpn_server", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'VPN Server'
#-----------------------------------------------------------------------------#
   lounge_switch_state:
     value_template: '{% if is_state("sensor.lounge_switch", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Lounge Switch'
#-----------------------------------------------------------------------------#
   bat_cave_switch_state:
     value_template: '{% if is_state("sensor.bat_cave_switch", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Bat Cave Switch'
#-----------------------------------------------------------------------------#
   poe_switch_state:
     value_template: '{% if is_state("sensor.poe_switch", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'POE Switch'
#-----------------------------------------------------------------------------#
   dining_room_wap_state:
     value_template: '{% if is_state("sensor.dining_room_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Dining Room WAP'        
#-----------------------------------------------------------------------------#
   kitchen_wap_state:
     value_template: '{% if is_state("sensor.kitchen_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Kitchen WAP'        
#-----------------------------------------------------------------------------#
   lounge_wap_state:
     value_template: '{% if is_state("sensor.lounge_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Lounge WAP'        
#-----------------------------------------------------------------------------#
   hallway_wap_state:
     value_template: '{% if is_state("sensor.hallway_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Hallway WAP'        
#-----------------------------------------------------------------------------#
   bedroom_wap_state:
     value_template: '{% if is_state("sensor.bedroom_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'Bedroom WAP'        
#-----------------------------------------------------------------------------#
   the_burrow_wap_state:
     value_template: '{% if is_state("sensor.the_burrow_wap", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'The Burrow WAP'        
#-----------------------------------------------------------------------------#
   dns_1_state:
     value_template: '{% if is_state("sensor.dns_1", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'DNS 1'        
#-----------------------------------------------------------------------------#
   dns_2_state:
     value_template: '{% if is_state("sensor.dns_2", "1") %}Up{% else %}Down{% endif %}'
     friendly_name: 'DNS 2'        
#-----------------------------------------------------------------------------#
#   ip_camera_server_state:
#     value_template: '{% if is_state("sensor.ip_camera_server", "1") %}Up{% else %}Down{% endif %}'
#     friendly_name: 'IP Camera Server'        
###############################################################################
