# Updated 19-11-2017
# Added Server ID

###############################################################################
# Speed Test
###############################################################################
- platform: speedtest
  server_id: "7028" # Sevenoaks
  #server_id: "16379" # Middlesbrough
  #server_id: "11547" # London
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload
###############################################################################
      