# Updated 21-11-2018
# Path = /config/sensors/time_date.yaml

###############################################################################
# Time & Date Sensor
###############################################################################
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    #- 'date_time'
    #- 'time_date'
    #- 'time_utc'
    #- 'beat'
###############################################################################      