# Updated 24-03-2019
# Path = /config/automation/alarm.yaml
# See Also /config/scripts/alarm.yaml

# First Crack at setting up an alarm 21-02-2019
# Turn off automation.alarm_reset 24-03-2019

###############################################################################
# Automations to control the Burglar Alarm #
###############################################################################

###############################################################################
# Front Door Sensor #
###############################################################################
- alias: 'Alarm Live Frontdoor'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.alarm_front_door
      to: 'on'
      #from: 'off'
  action:
     - service: script.turn_on
       data:
         entity_id:
           - script.front_door_alarm      

###############################################################################
# Motion Sensors #
###############################################################################
- alias: 'Alarm Live Motion'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.alarm_amy_bedroom
        - binary_sensor.alarm_hallway
        - binary_sensor.alarm_lounge      
        - binary_sensor.alarm_kitchen
        - binary_sensor.alarm_office
        - binary_sensor.alarm_dining_room
      to: 'on'
      #from: 'off'
  action:
     - service: script.turn_on
       data:
         entity_id: 
           - script.motion_detection_alarm
     #- service: notify.alarm      
     - service: notify.ralph_email
       data_template:
         title: "Alarm"
         message: "Sorry to disturb you Sir, but the {{ trigger.to_state.attributes.friendly_name }} has been activated it seems we have an intruder"                 

###############################################################################
# Reset after alarm has been triggered #
###############################################################################
- alias: 'Alarm Reset'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.alarm_front_door
        - binary_sensor.alarm_amy_bedroom
        - binary_sensor.alarm_hallway
        - binary_sensor.alarm_lounge      
        - binary_sensor.alarm_kitchen
        - binary_sensor.alarm_office
        - binary_sensor.alarm_dining_room
      to: 'off'
      from: 'on'
      for: '00:02:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.test_led_2 #Pretend Siren
          #- switch.alarm_siren
###############################################################################

###############################################################################
# Turn the alarm on #
###############################################################################    
- alias: 'Alarm On'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        #- binary_sensor.test_switch 
        - switch.alarm_armed
      to: 'on'
      #from: 'off'
  action:
     - service: script.turn_on
       data:
         entity_id: 
           -  script.alarm_on

###############################################################################
# Turn the alarm off #
###############################################################################    
- alias: 'Alarm Off'
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        #- binary_sensor.test_switch 
        - switch.alarm_armed
      to: 'off'
      #from: 'on'
  action:
     # Actions are scripts so can also be a list of actions
     - service: automation.turn_off
       data:    
         entity_id: 
           - automation.alarm_live_frontdoor
           - automation.alarm_live_motion
           - automation.alarm_reset
     - service: script.turn_off
       data:
         entity_id: 
           - script.front_door_alarm
           - script.motion_detection_alarm
           -  script.alarm_on
     - service: switch.turn_off
       data:
         entity_id: 
           - switch.test_led_2
           #- switch.alarm_siren
###############################################################################                  
