# Updated 31-10-2017
# Path = /config/automation/butterfly_lights.yaml

###############################################################################
# Automations to control the Butterfly lights in the Kitchen #
###############################################################################
- alias: 'Butterfly Lights On Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset   
  action:
    service: light.turn_on
    entity_id: light.butterfly_lights
#-----------------------------------------------------------------------------#
- alias: 'Butterfly Lights Off Evening'
  initial_state: True
  trigger:
     platform: time
     #after: '23:00:00'
     at: '23:59:00'
  action:
    service: light.turn_off
    entity_id: light.butterfly_lights
#-----------------------------------------------------------------------------#
- alias: 'Butterfly Lights On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise            
  action:
    service: light.turn_on
    entity_id: light.butterfly_lights
#-----------------------------------------------------------------------------#
- alias: 'Butterfly Lights off Morning'
  initial_state: True
  trigger:
     platform: sun
     event: sunrise
     #offset
  action:
    service: light.turn_off
    entity_id: light.butterfly_lights
###############################################################################                       
