# Updated 12-03-2019
# Path = /config/automation/christmas.yaml

# Merged all the Christmas Automations into one file
# Breaking change with V0.89.0 Renamed all the TP link switches
# Added automation to Activate Christmas Automations 12-03-2019

###############################################################################
# Activate Christmas #
###############################################################################    
- alias: 'Activate Christmas Pre New Year'
  initial_state: True
  trigger:
      - platform: template
        value_template: >-
          {{ now().strftime('%F') >= (now().strftime('%Y') | int ) ~ "-11-25" 
          and now().strftime('%F') <= (now().strftime('%Y') | int ) ~ "-12-31" }}
  action:
     # Actions are scripts so can also be a list of actions
     - service: automation.turn_on
       data:    
         entity_id: 
           - group.christmas_automations
#-----------------------------------------------------------------------------#    
- alias: 'Activate Christmas Post New Year'
  initial_state: True
  trigger:
      - platform: template
        value_template: >-
          {{ now().strftime('%F') >= (now().strftime('%Y') | int ) ~ "-01-01" 
          and now().strftime('%F') <= (now().strftime('%Y') | int ) ~ "-01-13" }}
  action:
     # Actions are scripts so can also be a list of actions
     - service: automation.turn_on
       data:    
         entity_id: 
           - group.christmas_automations
###############################################################################
# De-Activate Christmas #
###############################################################################    
- alias: 'De-Activate Christmas'
  initial_state: True
  trigger:
      - platform: template
        value_template: >-
          {{ now().strftime('%F') == (now().strftime('%Y') | int ) ~ "-01-14" }}
  action:
     # Actions are scripts so can also be a list of actions
     - service: automation.turn_off
       data:    
         entity_id: 
           - group.christmas_automations
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights
###############################################################################  


###############################################################################
# Automations for Christmas #
###############################################################################
###############################################################################
# Christmas Inside #
###############################################################################
- alias: 'Christmas Inside On Weekend'
  initial_state: False
  trigger:
     platform: time
     at: '07:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_on
       data:    
         entity_id: 
           - group.christmas_lights_inside
#-----------------------------------------------------------------------------#    
- alias: 'Christmas Inside Off Weekend'
  initial_state: False
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights_inside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Inside On Weekday AM'
  initial_state: False
  trigger:
     platform: time
     at: '06:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_on
       data:    
         entity_id: 
           - group.christmas_lights_inside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Inside Off Weekday AM'
  initial_state: False
  trigger:
     platform: time
     at: '09:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights_inside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Inside On Weekday PM'
  initial_state: False
  trigger:
     platform: time
     at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_on
       data:    
         entity_id: 
           - group.christmas_lights_inside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Inside Off Weekday PM'
  initial_state: False
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights_inside
###############################################################################

###############################################################################
# Christmas Outside #
###############################################################################
- alias: 'Christmas Outside on Evening'
  initial_state: False
  trigger:
     platform: sun
     event: sunset   
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_on
       data:    
         entity_id: 
           - group.christmas_lights_outside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Outside Off Evening'
  initial_state: False
  trigger:
     platform: time
     at: '23:00:00'
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights_outside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Outside On Morning'
  initial_state: False
  trigger:
     platform: time
     at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_on
       data:    
         entity_id: 
           - group.christmas_lights_outside
#-----------------------------------------------------------------------------#
- alias: 'Christmas Outside off Morning'
  initial_state: False
  trigger:
     platform: sun
     event: sunrise
  action:
     # Actions are scripts so can also be a list of actions
     - service: switch.turn_off
       data:    
         entity_id: 
           - group.christmas_lights_outside
###############################################################################

