# Updated 11-05-2018
# Merged all the Christmas Automations into one file

###############################################################################
# Automations for Christmas #
###############################################################################
###############################################################################
# Christmas Back Porch #
###############################################################################
- alias: 'Christmas Back Porch On Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '07:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
    service: switch.turn_on
    entity_id: switch.christmas_back_porch
#-----------------------------------------------------------------------------#    
- alias: 'Christmas Back Porch Off Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
    service: switch.turn_off
    entity_id: switch.christmas_back_porch
#-----------------------------------------------------------------------------#
- alias: 'Christmas Back Porch On Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_back_porch
#-----------------------------------------------------------------------------#
- alias: 'Christmas Back Porch Off Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '09:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_back_porch
#-----------------------------------------------------------------------------#
- alias: 'Christmas Back Porch On Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_back_porch
#-----------------------------------------------------------------------------#
- alias: 'Christmas Back Porch Off Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_back_porch
###############################################################################
    
###############################################################################
# Automation Christmas The Front Garden #
###############################################################################
- alias: 'Christmas Front Garden on Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset   
  action:
    service: switch.turn_on
    entity_id: switch.christmas_front_garden
#-----------------------------------------------------------------------------#
- alias: 'Christmas Front Garden Off Evening'
  initial_state: True
  trigger:
     platform: time
     at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.christmas_front_garden
#-----------------------------------------------------------------------------#
- alias: 'Christmas Front Garden On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_front_garden
#-----------------------------------------------------------------------------#
- alias: 'Christmas Front Garden off Morning'
  initial_state: True
  trigger:
     platform: time
     at: '08:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.christmas_front_garden
###############################################################################

###############################################################################
# Christmas The Lounge Window #
###############################################################################
- alias: 'Christmas Lounge Window on Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset   
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lounge_window
#-----------------------------------------------------------------------------#
- alias: 'Christmas Lounge Window Off Evening'
  initial_state: True
  trigger:
     platform: time
     at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.christmas_lounge_window
#-----------------------------------------------------------------------------#
- alias: 'Christmas Lounge Window On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lounge_window
#-----------------------------------------------------------------------------#
- alias: 'Christmas Lounge Window off Morning'
  initial_state: True
  trigger:
     platform: time
     at: '08:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.christmas_lounge_window
###############################################################################

###############################################################################
# Christmas in the Bat Cave #
###############################################################################
# Reset Christmas The Bat Cave lights because the lights have a shorter on/off 
# timer built in
###############################################################################
- alias: 'Christmas The Bat Cave On Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '07:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekend Reset'
  initial_state: True
  trigger:
     platform: time
     at: '14:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave On Weekend Reset'
  initial_state: True
  trigger:
     platform: time
     at: '14:01:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekend Reset II'
  initial_state: True
  trigger:
     platform: time
     at: '20:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave On Weekend Reset II'
  initial_state: True
  trigger:
     platform: time
     at: '20:01:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave On Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '09:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave On Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekday PM Reset'
  initial_state: True
  trigger:
     platform: time
     at: '18:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave On Weekday PM Reset'
  initial_state: True
  trigger:
     platform: time
     at: '18:01:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_the_bat_cave
#-----------------------------------------------------------------------------#
- alias: 'Christmas The Bat Cave Off Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_the_bat_cave
###############################################################################

###############################################################################
# Christmas Tree #
###############################################################################
- alias: 'Christmas Tree On Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '07:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun     
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree
#-----------------------------------------------------------------------------#
- alias: 'Christmas Tree Off Weekend'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun  
  action:
    service: switch.turn_off
    entity_id: switch.christmas_tree
#-----------------------------------------------------------------------------#
- alias: 'Christmas Tree On Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree
#-----------------------------------------------------------------------------#
- alias: 'Christmas Tree Off Weekday AM'
  initial_state: True
  trigger:
     platform: time
     at: '09:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_tree
#-----------------------------------------------------------------------------#
- alias: 'Christmas Tree On Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree
#-----------------------------------------------------------------------------#
- alias: 'Christmas Tree Off Weekday PM'
  initial_state: True
  trigger:
     platform: time
     at: '23:59:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri        
  action:
    service: switch.turn_off
    entity_id: switch.christmas_tree
###############################################################################
