# Modified 19-05-2018

###############################################################################
# Automations for Comms Cupboard Fan 
###############################################################################
- alias: 'Comms Cupboard Fan On' 
  initial_state: True
  trigger:
    platform: numeric_state
    entity_id: sensor.comms_temperature
    above: '28.9'
  action:
    service: switch.turn_on
    entity_id: switch.comms_fan
#-----------------------------------------------------------------------------#
- alias: 'Comms Cupboard Fan Off'
  initial_state: True 
  trigger:
    platform: numeric_state
    entity_id: sensor.comms_temperature
    below: '28.0'
  action:
    service: switch.turn_off
    entity_id: switch.comms_fan
###############################################################################
    