# Updated 20-04-2019
# Path = /config/automation/door_bell.yaml

# Ring the door bell and pause the TV & DVD
# Now using Google Chromecast Audio 02-03-2019
# Changed to a single automation remove TV stuff for now 05-03-2019
# Added Snapshot photo with email notification 11-04-2019
# Added IOS notification 20-04-2019

###############################################################################
# Door Bell 
###############################################################################
- alias: 'Door Bell'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.door_bell
    to: 'on'
  action:
   - service: media_player.volume_set
     data_template:
       entity_id:
           group.door_bell
       volume_level: 0.8
#       volume_level: 0.1
   - service: media_player.play_media
     data:
       entity_id: 
           group.door_bell
       media_content_id: >-
         http://192.168.0.22:8123/local/sounds/door_bell/doorbell.mp3
       media_content_type: music
   - service: camera.snapshot
     data:
       entity_id: camera.front_door
       filename: '/config/www/cameras/front_door/snapshot/snaphot.jpg'
   - service: notify.doorbell_ios
     data:
       title: "Someone is at the door"
       message: 'Someone is at the door'
       data:
         attachment:
           content-type: jpeg
           url: !secret door_bell_snapshot
   - service: notify.doorbell_email
     data:
       title: "Someone is at the door"
       message: 'Someone is at the door'
       data:
           images:
               - /config/www/cameras/front_door/snapshot/snaphot.jpg
###############################################################################


