# Updated 30-04-2017
# Ring the door bell and pause the TV & DVD

###############################################################################
# Automations for the Door Bell #
###############################################################################
- alias: 'Ring Door Bell Start'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.door_bell
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.ring_door_bell, script.pause_sky, script.pause_dvd, script.pause_apple_tv
###############################################################################
    
        