# Updated 26-01-2019
# Path = /config/automation/fireplace.yaml

###############################################################################
# Automations for the Fire Place Lights #
###############################################################################
- alias: 'Fire Place On Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset   
  action:
    service: light.turn_on
    entity_id: group.lights_fireplace
#-----------------------------------------------------------------------------#
- alias: 'Fire Place Off Evening'
  initial_state: True
  trigger:
     platform: time
     #after: '23:00:00'
     at: '23:59:00'
  action:
    service: light.turn_off
    entity_id: group.lights_fireplace
#-----------------------------------------------------------------------------#
- alias: 'Fire Place On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise            
  action:
    service: light.turn_on
    entity_id: group.lights_fireplace
#-----------------------------------------------------------------------------#
- alias: 'Fire Place off Morning'
  initial_state: True
  trigger:
     platform: sun
     event: sunrise
     #offset	
  action:
    service: light.turn_off
    entity_id: group.lights_fireplace
###############################################################################
