# Updated 26-11-2017

###############################################################################
# Automations for the Fire Place Lights #
###############################################################################
- alias: 'Fire Place On Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset   
  action:
    service: switch.turn_on
    entity_id: switch.fireplace_red, switch.fireplace_white
#-----------------------------------------------------------------------------#
- alias: 'Fire Place Off Evening'
  initial_state: True
  trigger:
     platform: time
     #after: '23:00:00'
     at: '23:59:00'
  action:
    service: switch.turn_off
    entity_id: switch.fireplace_red, switch.fireplace_white
#-----------------------------------------------------------------------------#
- alias: 'Fire Place On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise            
  action:
    service: switch.turn_on
    entity_id: switch.fireplace_red, switch.fireplace_white
#-----------------------------------------------------------------------------#
- alias: 'Fire Place off Morning'
  initial_state: True
  trigger:
     platform: sun
     event: sunrise
     #offset	
  action:
    service: switch.turn_off
    entity_id: switch.fireplace_red, switch.fireplace_white
###############################################################################
