# Updated 07-03-2019
# Path = /config/automation/lounge_pyramid_light.yaml

# Breaking change with V0.89.0 Renamed all the TP link switches

###############################################################################
# Automations to control the Lounge Pyramid Light #
###############################################################################
- alias: 'Lounge Pyramid Light On Evening'
  initial_state: True
  trigger:
     platform: sun
     event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.tp_8
#-----------------------------------------------------------------------------#
- alias: 'Lounge Pyramid Light Off Evening'
  initial_state: True
  trigger:
     platform: time
     #after: '23:00:00'
     at: '23:59:00'
  action:
    service: switch.turn_off
    entity_id: switch.tp_8
#-----------------------------------------------------------------------------#
- alias: 'Lounge Pyramid Light On Morning'
  initial_state: True
  trigger:
     platform: time
     at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
  action:
    service: switch.turn_on
    entity_id: switch.tp_8
#-----------------------------------------------------------------------------#
- alias: 'Lounge Pyramid Light off Morning'
  initial_state: True
  trigger:
     platform: sun
     event: sunrise
     #offset
  action:
    service: switch.turn_off
    entity_id: switch.tp_8
###############################################################################                       
