# Updated 19-04-2018
# Monitor critical network components
# Added DNS Server & Computer Room Switch 20-03-2018
# Added 2nd DNS Server 25-03-2018
# Changed Email Settings 15-04-2018
# Changed notification to notify group 19-04-2018
# Network Changes 02-06-2018

###############################################################################
# Automation for Network Monitoring Notification #
###############################################################################
- alias: 'POE Switch Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.poe_switch_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "POE Switch Down"
      message: "Sorry to disturb you Sir, but the POE Switch seems to be Down"
#-----------------------------------------------------------------------------#      
#- alias: 'ADSL Line 1 Down'
#  initial_state: True
#  trigger:
#     platform: state
#     entity_id: sensor.adsl_line_1_state
#     to: 'Down'
#     for:
#        hours: 0
#        minutes: 2
#        seconds: 0
#  action:
#    service: notify.ralph
#    data:
#      title: "ADSL line 1"
#      message: "Sorry to disturb you Sir, but ADSL Line 1 seems to be Down"
#-----------------------------------------------------------------------------#            
#- alias: 'ADSL Line 2 Down'
#  initial_state: True
#  trigger:
#     platform: state
#     entity_id: sensor.adsl_line_2_state
#     to: 'Down'
#     for:
#        hours: 0
#        minutes: 2
#        seconds: 0
#  action:
#    service: notify.ralph
#    data:
#      title: "ADSL line 2"
#      message: "Sorry to disturb you Sir, but ADSL Line 2 seems to be Down"
#-----------------------------------------------------------------------------#   
- alias: 'VPN Server Is Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.vpn_server_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0 
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "VPN Server"
      message: "Sorry to disturb you Sir, but the VPN Server seems to be Down"
#-----------------------------------------------------------------------------#
- alias: 'DNS 1 Is Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.dns_1_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0 
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "DNS 1"
      message: "Sorry to disturb you Sir, but Domain Name Server 1 seems to be Down"
#-----------------------------------------------------------------------------#
- alias: 'DNS 2 Is Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.dns_2_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0 
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "DNS 2"
      message: "Sorry to disturb you Sir, but Domain Name Server 2 seems to be Down"
#-----------------------------------------------------------------------------#      
- alias: 'Lounge Switch Is Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.lounge_switch_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0 
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "Lounge Switch"
      message: "Sorry to disturb you Sir, but the Lounge Switch seems to be Down"
#-----------------------------------------------------------------------------#      
- alias: 'IP Camera Server Is Down'
  initial_state: True
  trigger:
     platform: state
     entity_id: sensor.ip_camera_server_state
     to: 'Down'
     for:
        hours: 0
        minutes: 0 
        seconds: 30
  action:
    service: notify.ralph
    data:
      title: "IP Camera Server"
      message: "Sorry to disturb you Sir, but the IP Camera Server seems to be Down"
#-----------------------------------------------------------------------------#
#- alias: 'Computer Room Switch Is Down'
#  initial_state: True
#  trigger:
#     platform: state
#     entity_id: sensor.computer_room_switch_state
#     to: 'Down'
#     for:
#        hours: 0
#        minutes: 0 
#        seconds: 30
#  action:
#    service: notify.ralph
#    data:
#      title: "Computer Room Switch"
#      message: "Sorry to disturb you Sir, but the Computer Room Switch seems to be Down"
###############################################################################
            
