# Updated 20-04-2019
# Path = /config/configuration.yaml

# Changed FireTV breaking change in V0.90 21-03-2019
# Removed http: api_password: !secret ha_api_password breaking change in V0.90 21-03-2019
# Split out History & Logbook 26-03-2019
# Created Dummy Camera to capture door bell image 19-04-2019
# Moved Media Players to a package 20-04-2019
# Moved cameras to separate file 20-04-2019

###############################################################################
homeassistant:
  # Name of the location where Home Assistant is running #
  name: Jarvis
  # Location required to calculate the time the sun rises and sets #
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters) #
  elevation: 102
  # metric for Metric, imperial for Imperial #
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages
  # New Authentication Method
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - !secret trusted_network
###############################################################################

###############################################################################
# HTTP Access 
###############################################################################
http:
  server_port: !secret ha_port
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy
  ip_ban_enabled: True
  login_attempts_threshold: 3
###############################################################################

###############################################################################
# Mosquitto MQTT Broker #
###############################################################################
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username   
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  protocol: 3.1
###############################################################################

###############################################################################
# Enable System Health component 
###############################################################################
system_health:
###############################################################################

###############################################################################
# Enable Python Scripts
###############################################################################
python_script:
###############################################################################

###############################################################################
# Logging #
###############################################################################
logger: !include logger.yaml
###############################################################################

###############################################################################
# Recorder #
###############################################################################
recorder: !include recorder.yaml
###############################################################################

###############################################################################
# Enables support for tracking state changes over time #
###############################################################################
history: !include history.yaml
###############################################################################

###############################################################################      
# View events in logbook #
###############################################################################
logbook: !include logbook.yaml
###############################################################################

###############################################################################
# Enables the frontend #
###############################################################################
frontend:
  #javascript_version: es5
  javascript_version: latest
#  javascript_version: auto
###############################################################################

###############################################################################
# Show links to resources in log and frontend #
#introduction:
###############################################################################

###############################################################################  
# Configuration Panel #
###############################################################################
config:
###############################################################################

###############################################################################
# Enable iOS App #
###############################################################################
ios:
###############################################################################

###############################################################################
# Checks for available updates #
###############################################################################
updater:
###############################################################################

###############################################################################
# Discover some devices automatically #
###############################################################################
#discovery:
###############################################################################

###############################################################################
# Allows you to issue voice commands from the frontend in enabled browsers #
###############################################################################
#conversation:
###############################################################################

###############################################################################
# Track the sun #
###############################################################################
sun:
###############################################################################

###############################################################################
# Notifications #
notify: !include_dir_merge_list notify
###############################################################################    
     
###############################################################################
# Zones #
###############################################################################
zone: !include zones.yaml
###############################################################################

###############################################################################
# Switches #
###############################################################################
switch: !include_dir_merge_list switches
###############################################################################

###############################################################################
# TP-Link #
###############################################################################
tplink: !include tp_link.yaml
###############################################################################

###############################################################################
# Lights #
###############################################################################
light: !include_dir_merge_list lights
###############################################################################

###############################################################################
# Scenes #
###############################################################################
#scene: !include_dir_merge_list scenes
###############################################################################

###############################################################################
# Automation #
###############################################################################
automation: !include_dir_merge_list automation            
###############################################################################

###############################################################################
# Input Select #
###############################################################################
#input_select: !include input_select.yaml
###############################################################################

###############################################################################
# Scripts #
###############################################################################
script: !include_dir_merge_named scripts
###############################################################################

###############################################################################
# Groups #
###############################################################################
group: !include groups.yaml
###############################################################################

###############################################################################
# Sensors #
###############################################################################
sensor: !include_dir_merge_list sensors
###############################################################################

###############################################################################
# Binary Sensors #
###############################################################################
binary_sensor: !include_dir_merge_list binary_sensors
###############################################################################

###############################################################################
# Internet Speed Test #
###############################################################################
speedtestdotnet:
  server_id: "7028" # Sevenoaks
  #server_id: "16379" # Middlesbrough
  #server_id: "11547" # London
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
###############################################################################

###############################################################################
# Text To Speech #
###############################################################################
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret polly_aws_access_key_id
    aws_secret_access_key: !secret polly_aws_secret_access_key
    region_name: eu-west-2
    output_format: mp3
    #voice: Amy
    voice: Brian
    cache: true
    cache_dir: /config/tts
    time_memory: 300
###############################################################################

###############################################################################
# Cameras #
###############################################################################
camera: !include_dir_merge_list cameras
###############################################################################

###############################################################################
# Media Players #
# Located at:
# /config/packages/media_players.yaml
###############################################################################
