sensor.ralphs_iphone_battery_level:
  name:
  platform: ios
  unique_id: level_ralph_daveys_iphone
sensor.ralphs_iphone_battery_state:
  name:
  platform: ios
  unique_id: state_ralph_daveys_iphone
switch.christmas_front_garden:
  name:
  platform: wemo
  unique_id: 221701K110019F
sensor.tracys_iphone_battery_level:
  name:
  platform: ios
  unique_id: level_tracys_iphone
sensor.tracys_iphone_battery_state:
  name:
  platform: ios
  unique_id: state_tracys_iphone
