# Updated 19-03-2019
# Path = /config/groups.yaml

# Updated Alarm Groups 20-02-2019
# Added Christmas Group 11-03-2019
# Added Doorbell 19-03-2019

###############################################################################    
# Groups     
###############################################################################
#-----------------------------------------------------------------------------#
  test_group:
    name: "Test Group"
    #control: hidden
    entities:
      - media_player.office_speaker
      #- media_player.mum_speaker
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
  door_bell:
    name: "Door Bell"
    #control: hidden
    entities:
      - media_player.hall_speaker
      - media_player.mum_speaker
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
  christmas_automations:
    name: "Christmas Automations"
    entities:
      - automation.christmas_inside_off_weekday_am
      - automation.christmas_inside_off_weekday_pm
      - automation.christmas_inside_off_weekend
      - automation.christmas_inside_on_weekday_am
      - automation.christmas_inside_on_weekday_pm
      - automation.christmas_inside_on_weekend
      - automation.christmas_outside_off_evening
      - automation.christmas_outside_off_morning
      - automation.christmas_outside_on_evening
      - automation.christmas_outside_on_morning
#-----------------------------------------------------------------------------#
  christmas_lights:
    name: "Christmas Lights"
    #control: hidden
    entities:
      - switch.tp_1 # Back Porch Laser
      - switch.tp_2 # Christmas Lounge Window
      - switch.tp_3 # Christmas Tree
      - switch.tp_4 # Christmas Back Porch
      - switch.tp_5 # Christmas Office
      - switch.tp_7 # Christmas Front Garden
#-----------------------------------------------------------------------------#
  christmas_lights_inside:
    name: "Christmas Lights Inside"
    #control: hidden
    entities:
      - switch.tp_3 # Christmas Tree
      - switch.tp_4 # Christmas Back Porch
      - switch.tp_5 # Christmas Office
#-----------------------------------------------------------------------------#
  christmas_lights_outside:
    name: "Christmas Lights Outside"
    #control: hidden
    entities:
      - switch.tp_2 # Christmas Lounge Window
      - switch.tp_7 # Christmas Front Garden
#-----------------------------------------------------------------------------#
  lights_external_dusk_dawn:
    name: "Lights External Dusk To Dawn"
    #control: hidden
    entities:
      - light.front_porch_light
      - light.soffit_lights
#-----------------------------------------------------------------------------#
  lights_fireplace:
    name: "Lights Fireplace"
    #control: hidden
    entities:
      - light.fireplace_red_light
      - light.fireplace_white_light
#-----------------------------------------------------------------------------#
  lights_front_door_open:
    name: "Lights Front Door Open"
    #control: hidden
    entities:
      - light.hallway_lights
      - light.front_garage_lights
#-----------------------------------------------------------------------------#
  burglar_alarm_motion_sensors:
    name: "Burglar Alarm Motion Sensors"
    #control: hidden
    entities:
      - binary_sensor.alarm_amy_bedroom
      - binary_sensor.alarm_hallway
      - binary_sensor.alarm_lounge      
      - binary_sensor.alarm_kitchen
      - binary_sensor.alarm_office
      - binary_sensor.alarm_dining_room
#-----------------------------------------------------------------------------#
  burglar_alarm_door_widow_sensors:
    name: "Burglar Alarm Door / Window Sensors"
    #control: hidden
    entities:
      - binary_sensor.alarm_front_door
#-----------------------------------------------------------------------------#
