# Updated 27-03-2019
# Path = /config/tp_link.yaml

# Breaking changes in V0.89.0
# Breaking change with V0.89.0 Renamed all the TP link switches
# Used DNS name instead of IP address to make error log easier to read 26-03-2019
# Changed back to IP address as HA floods the DNS server with requests :-) 27-03-2019
###############################################################################
discovery: false
###############################################################################


###############################################################################
# The are all the TP-Link Power Points                                        #
###############################################################################
switch:
###############################################################################

###############################################################################
# Installed in Mum's Loft for the Laser Display in The Back Porch #
###############################################################################
  - host: !secret tp_1
#  - host: tp-1
###############################################################################
# Installed in the Lounge For Christmas Lights #
###############################################################################
  - host: !secret tp_2
#  - host: tp-2
###############################################################################
# Installed in the Lounge For the Christmas Tree Lights #
###############################################################################
  - host: !secret tp_3
#  - host: tp-3
###############################################################################
# Installed in a Kitchen Cupboard for Christmas Lights in the back Porch #
###############################################################################
  - host: !secret tp_4
#  - host: tp-4
###############################################################################
# Installed in The Office for Christmas Lights in the Hallway & Office #
###############################################################################
  - host: !secret tp_5
#  - host: tp-5
###############################################################################
# Installed in The Bat Cave controls my Fan  #
###############################################################################
  - host: !secret tp_6
#  - host: tp-6
###############################################################################
# Installed in The Hallway Front Garden Christmas Lights / Garage  #
###############################################################################
  - host: !secret tp_7
#  - host: tp-7
###############################################################################
# Installed in The Lounge for Pyramid Light  #
###############################################################################
  - host: !secret tp_8
#  - host: tp-8
###############################################################################
