# Updated 19-02-2019
# Path = /config/binary_sensors/alarm_binary_sensors.yaml

# Check on line status the Two ESP8266's that control the Burglar Alarm
# Added additional ESP to control the Alarm NFC Reader 09-05-2018
# Changed QOS to 0 23-06-2018
# Changed Office Sensor Name 28-01-2019
# Removed "optimistic: false" & "retain: true" as it broke the sensors in V0.87.0 07-02-2019
# Replaced Wireless MCU's with a wired Raspberry ping 19-02-2019


###############################################################################
# Binary Sensors Alarm Sensors #
###############################################################################
- platform: mqtt
  name: "Alarm Amy Bedroom"
  state_topic: "alarm/input/front_bedroom_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#-----------------------------------------------------------------------------#  
- platform: mqtt
  name: "Alarm Dining Room"
  state_topic: "alarm/input/dining_room_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#-----------------------------------------------------------------------------#  
- platform: mqtt
  name: "Alarm Front Door"
  state_topic: "alarm/input/front_door"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: opening
#-----------------------------------------------------------------------------#
- platform: mqtt
  name: "Alarm Hallway"
  state_topic: "alarm/input/hallway_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#-----------------------------------------------------------------------------#
- platform: mqtt
  name: "Alarm Kitchen"
  state_topic: "alarm/input/kitchen_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#-----------------------------------------------------------------------------#
- platform: mqtt
  name: "Alarm Lounge"
  state_topic: "alarm/input/lounge_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
#-----------------------------------------------------------------------------#
- platform: mqtt
  name: "Alarm Office"
  state_topic: "alarm/input/office_sensor"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
###############################################################################
    