# Updated 02-03-2019
# Path = /config/binary_sensors/door_bell.yaml

# Triggered by bell_press.py from the front door Raspberry Pi Camera
# This triggers /automation/door_bell.yaml & ios_notify_door_bell.yaml
# Changed to Alarm RPI

###############################################################################
# Binary Sensor Door Bell #
###############################################################################
- platform: mqtt
  name: "Door Bell"
  state_topic: "alarm/input/door_bell_button"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  #device_class: motion
###############################################################################
