# Updated 27-05-2018 
# This is a test Binary Sensor using ESP-Easy on an ESP8266
# http://192.168.0.46

###############################################################################
# This is my TEST ESP-Easy Board for Lights & Switches
# See Also Switches Test Switch
###############################################################################
- platform: mqtt
  name: "Test Switch"
  state_topic: "/Test_ESP/Test_Switch/Switch"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  #device_class: opening
  #optimistic: false
  retain: true
###############################################################################
  