# Updated 06-04-2018
# Path = /config/binary_sensors/workday.yaml

###############################################################################
# Binary Sensor Workday & Holidays #
###############################################################################
- platform: workday
  country: England
###############################################################################


