# Updated 06-04-2018
###############################################################################
# Binary Sensor Workday & Holidays #
###############################################################################
- platform: workday
  country: England
###############################################################################


